---
- name: gathering facts
  hosts: all
  tasks:
    - name: creating hwtemplate.txt file with data
      template:
        src: hwtemplate.j2
        dest: /home/ansible/hwtemplate.txt
        owner: ansible
        group: ansible
        mode: '0644'
      delegate_to: localhost
